### ISSUE TITLE
Issue with restoring pinned and floating panels

### ISSUE THREAD

**Issue by barrettj** [louisdh/panelkit#15]
I'm not sure if this is due to how my project is set up, but I can't seem to have restoration work when there is both a pinned and a floating panel.

I'm calling my restorePanelStatesFromDisk() in viewWillAppear because if a panel is pinned I want it to be there as the view is being presented.  This doesn't seem to display floating panels, though.

Calling restorePanelStatesFromDisk() in viewDidAppear seems to display floating panels fine, but causes pinned panels to suddenly appear instead of being there from the initial display animation.

I've tried calling restorePanelStatesFromDisk() in both, but this causes pinned panels to be there at the start but then disappear.

Any insights into what I might be doing wrong?

Thanks!

**Comment by louisdh** [comment]
Just checked in Pixure, and I call `restorePanelStatesFromDisk()` from `viewDidLoad`. It's safe to do since the layout of the panels is done entirely with Auto Layout. When restoring the states of your panels, can you check if your manager returns `true` for `allowFloatingPanels` and `allowPanelPinning`?

**Comment by barrettj** [comment]
After moving restorePanelStatesFromDisk to just being called in viewDidLoad everything seems to be working as expected (allow pinning and floating were both always true).  Not sure where I got the idea to do willAppear from instead of didLoad from.

Thanks!
